### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by dongqi-me** [shallinan1/STEERStyleTransfer#1]
Hi,

It is good to read your paper, may I know when you plan to release your code? 

Many thanks!

**Comment by shallinan1** [comment]
Thanks for the interest! I will target releasing this by week. Thanks for your patience

**Comment by soummyaah** [comment]
Hi @shallinan1,

It was interesting to read your paper. Would you be releasing the code soon?

Thanks,

**Comment by shallinan1** [comment]
Thanks, yes it is now available. Please feel free to raise another issue if there are any more questions!
